from fastapi import APIRouter, HTTPException
from datetime import datetime
import logging
from typing import Optional
from src.api.schemas import (
    LocationData, ScheduleRequest, InterventionRequest, 
    ResetInterventionRequest, SprayRecord
)
from src.api.dependencies import (
    get_ai_recommender, get_spray_scheduler, get_db_manager, get_data_integrator
)

router = APIRouter()
logger = logging.getLogger(__name__)

@router.post("/ai-recommend-treatment")
async def ai_recommend_treatment(
    disease: str,
    confidence: float,
    location: LocationData,
    growth_stage: Optional[str] = "Vegetative"
):
    """
    Get AI-powered treatment recommendations
    """
    try:
        # Get real-time context
        integrator = get_data_integrator()
        context = integrator.get_complete_context(
            location.name, 
            location.latitude, 
            location.longitude
        )
        
        recommender = get_ai_recommender()
        
        recommendations = recommender.predict_treatment(
            disease=disease,
            confidence=confidence,
            weather=context['current_weather'],
            location_profile=context.get('location_profile'),
            growth_stage=growth_stage,
            top_k=5
        )
        
        return {
            "success": True,
            "disease": disease,
            "detection_confidence": confidence,
            "location": location.name,
            "current_weather": context['current_weather'],
            "recommendations": recommendations,
            "growth_stage": growth_stage,
            "timestamp": datetime.now().isoformat(),
            "note": "Recommendations generated by AI model trained on historical outcomes"
        }
        
    except Exception as e:
        logger.error(f"AI recommendation error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/create-spray-schedule")
async def create_spray_schedule(request: ScheduleRequest):
    """
    Generate automated spray schedule using RL-based optimizer
    """
    try:
        scheduler = get_spray_scheduler()
        
        scheduler_result = scheduler.create_schedule(
            location=request.location.name,
            days_ahead=request.days_ahead
        )
        
        next_spray = scheduler.get_next_spray_date()
        alerts = scheduler.send_alerts(scheduler_result['schedule'])
        
        return {
            "success": True,
            "location": request.location.name,
            "schedule": scheduler_result['schedule'],
            "summary": scheduler_result['summary'],
            "next_spray": next_spray,
            "alerts": alerts,
            "timestamp": datetime.now().isoformat()
        }
        
    except Exception as e:
        logger.error(f"Schedule creation error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/record-intervention")
async def record_intervention(request: InterventionRequest):
    """Record a spray or other intervention"""
    try:
        db = get_db_manager()
        success = db.add_record({
            "user_id": request.user_id,
            "date": request.date,
            "type": request.type,
            "name": "Manual Spray",
            "quantity": 1.0,
            "notes": "Recorded via App"
        })
        
        return {"success": success}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/reset-intervention")
async def reset_intervention(request: ResetInterventionRequest):
    """Reset recent spray history (Undo)"""
    try:
        db = get_db_manager()
        success = db.clear_recent_interventions(request.user_id)
        return {"success": success}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/spray/record")
async def record_spray(record: SprayRecord):
    """
    Record a spray event and update risk calculation
    """
    try:
        db = get_db_manager()
        success = db.add_record(record.dict())
        
        if not success:
            raise HTTPException(status_code=500, detail="Failed to save record")
            
        return {
            "status": "success",
            "message": "Spray recorded. Risk levels updated.",
            "updated_risk_factor": 0.1
        }
    except Exception as e:
        logger.error(f"Error recording spray: {e}")
        raise HTTPException(status_code=500, detail=str(e))
